
package org.example.ws_ht.api.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 07 20:30:48 ART 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "illegalOperation", targetNamespace = "http://www.example.org/WS-HT/api/xsd")
public class IllegalOperationFault extends Exception {
    public static final long serialVersionUID = 20110207203048L;
    
    private java.lang.String illegalOperation;

    public IllegalOperationFault() {
        super();
    }
    
    public IllegalOperationFault(String message) {
        super(message);
    }
    
    public IllegalOperationFault(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalOperationFault(String message, java.lang.String illegalOperation) {
        super(message);
        this.illegalOperation = illegalOperation;
    }

    public IllegalOperationFault(String message, java.lang.String illegalOperation, Throwable cause) {
        super(message, cause);
        this.illegalOperation = illegalOperation;
    }

    public java.lang.String getFaultInfo() {
        return this.illegalOperation;
    }
}
