
package org.example.ws_ht.api.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 07 20:30:48 ART 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "illegalArgument", targetNamespace = "http://www.example.org/WS-HT/api/xsd")
public class IllegalArgumentFault extends Exception {
    public static final long serialVersionUID = 20110207203048L;
    
    private java.lang.String illegalArgument;

    public IllegalArgumentFault() {
        super();
    }
    
    public IllegalArgumentFault(String message) {
        super(message);
    }
    
    public IllegalArgumentFault(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalArgumentFault(String message, java.lang.String illegalArgument) {
        super(message);
        this.illegalArgument = illegalArgument;
    }

    public IllegalArgumentFault(String message, java.lang.String illegalArgument, Throwable cause) {
        super(message, cause);
        this.illegalArgument = illegalArgument;
    }

    public java.lang.String getFaultInfo() {
        return this.illegalArgument;
    }
}
