
package org.example.ws_ht.api.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 07 20:30:48 ART 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "illegalState", targetNamespace = "http://www.example.org/WS-HT/api/xsd")
public class IllegalStateFault extends Exception {
    public static final long serialVersionUID = 20110207203048L;
    
    private org.example.ws_ht.api.xsd.IllegalState illegalState;

    public IllegalStateFault() {
        super();
    }
    
    public IllegalStateFault(String message) {
        super(message);
    }
    
    public IllegalStateFault(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalStateFault(String message, org.example.ws_ht.api.xsd.IllegalState illegalState) {
        super(message);
        this.illegalState = illegalState;
    }

    public IllegalStateFault(String message, org.example.ws_ht.api.xsd.IllegalState illegalState, Throwable cause) {
        super(message, cause);
        this.illegalState = illegalState;
    }

    public org.example.ws_ht.api.xsd.IllegalState getFaultInfo() {
        return this.illegalState;
    }
}
