
package org.example.ws_ht.api.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 07 20:30:48 ART 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "illegalAccess", targetNamespace = "http://www.example.org/WS-HT/api/xsd")
public class IllegalAccessFault extends Exception {
    public static final long serialVersionUID = 20110207203048L;
    
    private java.lang.String illegalAccess;

    public IllegalAccessFault() {
        super();
    }
    
    public IllegalAccessFault(String message) {
        super(message);
    }
    
    public IllegalAccessFault(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalAccessFault(String message, java.lang.String illegalAccess) {
        super(message);
        this.illegalAccess = illegalAccess;
    }

    public IllegalAccessFault(String message, java.lang.String illegalAccess, Throwable cause) {
        super(message, cause);
        this.illegalAccess = illegalAccess;
    }

    public java.lang.String getFaultInfo() {
        return this.illegalAccess;
    }
}
