
package org.example.ws_ht.api.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 07 20:30:48 ART 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "recipientNotAllowed", targetNamespace = "http://www.example.org/WS-HT/api/xsd")
public class RecipientNotAllowed extends Exception {
    public static final long serialVersionUID = 20110207203048L;
    
    private java.lang.String recipientNotAllowed;

    public RecipientNotAllowed() {
        super();
    }
    
    public RecipientNotAllowed(String message) {
        super(message);
    }
    
    public RecipientNotAllowed(String message, Throwable cause) {
        super(message, cause);
    }

    public RecipientNotAllowed(String message, java.lang.String recipientNotAllowed) {
        super(message);
        this.recipientNotAllowed = recipientNotAllowed;
    }

    public RecipientNotAllowed(String message, java.lang.String recipientNotAllowed, Throwable cause) {
        super(message, cause);
        this.recipientNotAllowed = recipientNotAllowed;
    }

    public java.lang.String getFaultInfo() {
        return this.recipientNotAllowed;
    }
}
