
package proxy.hise.apache.org.wsdl.ws_humantask_proxy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 07 20:30:44 ART 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "standardFault", targetNamespace = "http://hise.apache.org/schema/ws-humantask-proxy-api")
public class CompleteFault extends Exception {
    public static final long serialVersionUID = 20110207203044L;
    
    private org.apache.hise.schema.ws_humantask_proxy_api.StandardFault standardFault;

    public CompleteFault() {
        super();
    }
    
    public CompleteFault(String message) {
        super(message);
    }
    
    public CompleteFault(String message, Throwable cause) {
        super(message, cause);
    }

    public CompleteFault(String message, org.apache.hise.schema.ws_humantask_proxy_api.StandardFault standardFault) {
        super(message);
        this.standardFault = standardFault;
    }

    public CompleteFault(String message, org.apache.hise.schema.ws_humantask_proxy_api.StandardFault standardFault, Throwable cause) {
        super(message, cause);
        this.standardFault = standardFault;
    }

    public org.apache.hise.schema.ws_humantask_proxy_api.StandardFault getFaultInfo() {
        return this.standardFault;
    }
}
