package proxy.hise.apache.org.wsdl.ws_humantask_proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 07 20:30:44 ART 2011
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://org.apache.hise.proxy/wsdl/ws-humantask-proxy", name = "ws-humantask-proxyPortType")
@XmlSeeAlso({org.apache.hise.schema.ws_humantask_proxy_api.ObjectFactory.class, org.example.ws_ht.api.ObjectFactory.class, org.example.ws_ht.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WsHumantaskProxyPortType {

    @WebResult(name = "completeResponse", targetNamespace = "http://hise.apache.org/schema/ws-humantask-proxy-api", partName = "completeResponsePart")
    @WebMethod
    public org.apache.hise.schema.ws_humantask_proxy_api.CompleteResponse complete(
        @WebParam(partName = "completeRequestPart", name = "completeRequest", targetNamespace = "http://hise.apache.org/schema/ws-humantask-proxy-api")
        org.apache.hise.schema.ws_humantask_proxy_api.CompleteRequest completeRequestPart
    ) throws CompleteFault;

    @WebResult(name = "getTaskResponse", targetNamespace = "http://hise.apache.org/schema/ws-humantask-proxy-api", partName = "getTaskResponse")
    @WebMethod
    public org.apache.hise.schema.ws_humantask_proxy_api.GetTaskResponse getTask(
        @WebParam(partName = "getTaskRequestPart", name = "getTaskRequest", targetNamespace = "http://hise.apache.org/schema/ws-humantask-proxy-api")
        org.apache.hise.schema.ws_humantask_proxy_api.GetTaskRequest getTaskRequestPart
    ) throws GetTaskFault;
}
