package org.example.ws_ht.protocol.wsdl;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 07 20:30:45 ART 2011
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://www.example.org/WS-HT/protocol/wsdl", name = "humanTaskParticipantPortType")
@XmlSeeAlso({org.example.ws_ht.protocol.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HumanTaskParticipantPortType {

    @Oneway
    @WebMethod
    public void exitOperation(
        @WebParam(partName = "parameters", name = "exit", targetNamespace = "http://www.example.org/WS-HT/protocol")
        org.example.ws_ht.protocol.ProtocolMsgType parameters
    );
}
